### ISSUE TITLE
Feature Request: Steam Controller

### ISSUE THREAD

**Issue by Krutonium** [kmicki/SteamDeckGyroDSU#61] opened 2023-10-24 23:02 UTC
Would it be possible to add support for the Gyro in the Steam Controller, interchangeable with the gyro in the Deck? Like automatically switching?

**Comment by kmicki** [comment] 2023-10-31 07:42
Duplicate of #41

**Comment by kmicki** [comment] 2024-03-28 10:59
Closing as duplicate - see #41

**Closed by kmicki** 2024-03-28 10:59 UTC
Labels: duplicate, enhancement
