### ISSUE TITLE
No motion detected on latest steam client

### ISSUE THREAD

**Issue by fivezeroes** [kmicki/SteamDeckGyroDSU#45] opened 2023-04-12 03:20 UTC
While using the latest steam client beta, no gyro movement is being registered. I've tried reinstalling, rebooting, confirmed the service is running, and tested with both cemu and yuzu. After switching back to steam stable, gyro works as expected.

**Comment by Mario-119** [comment] 2023-04-14 20:11
Can confirm the same behavior, replicated all of the above steps

**Comment by kmicki** [comment] 2023-04-17 11:56
Yes there is a problem with new Beta. Steam disables gyro input from the controller when Gyro in controller settings is set to "None".

As a workaround (I assume Cemu/Yuzu is run in gaming mode from Steam):
1. Press STEAM button
2. Open Controller Settings
3. Edit layout
4. Go to Gyro
5. Select Gyro Behavior -> Directional Pad
6. Choose anything for one of the positions of directional pad. Anything that won't intefere with using Cemu/Yuzu. I chose Action Sets->Cleared from Parent
7. Now it should work.

**Comment by ich777** [comment] 2023-04-20 18:32
@kmicki rhat doesn‘t work either, i did it exactly like you‘ve described it, I even tried to set the gyro to be always activated but no dice.
Yuzu tells me that it received inputs when i move the deck.

**Comment by kmicki** [comment] 2023-04-20 18:34
Well, I don't know what to say, it works for me in Cemu.

**Comment by kuar-z** [comment] 2023-04-21 22:55
Additional data: motion IS detected without the workaround above but ONLY when the Steam overlay is enabled. Hope this helps narrow it down.

**Comment by kmicki** [comment] 2023-04-22 05:28
Thanks. Yes, I have also noticed that gyro data is present when overlay is open.

I wasn't clear before. The issue is already identified. There's nothing else that can be done besides using the workaround or coming up with a completely different approach (I don't not what would that be right now) and rewriting most of `sdgyrodsu`.

Steam application sends commands to the controller to enable or disable gyro data. `sdgyrodsu` is not able to intercept or simulate those commands. Steam app has full write access to the device and `sdgyrodsu` can only look at data incoming from the controller.

**Comment by ich777** [comment] 2023-04-22 06:25
Grimbakor from the Yuzu Discord has made a video on how to enable it, the main issue was that you have to click the button in the middle in the Controller settings in Yuzu and not on the other option which most Youtube videos recommend.
He allowed me to upload his videos here.

This is if you are doing it from the Desktop mode (you have to make the screen actually bigger because otherwise you won't be able to click the button):

https://user-images.githubusercontent.com/28066518/233766603-c1b17863-588a-4e03-8358-d1fd0c64432a.mp4


And this is what you have to do when you do it from within Gaming Mode (you have to set a custom resolution in order to be able to click the button):

https://user-images.githubusercontent.com/28066518/233766614-a6376af8-c053-4ba2-b764-639ac70bd64b.mp4


BTW, I don't have to do the workaround that you've posted above @kmicki, the gyro is in my case always active even when using a Controller layout without Gyro.

**Comment by KrisCris** [comment] 2023-04-22 06:33
> Select Gyro Behavior -> Directional Pad

I can confirm this is the ONLY step needed for me to get the gyro working, for both Cemu and Yuzu.

Can also confirm the gyro works when an overlay (like the quick access menu) is open.

**Comment by kmicki** [comment] 2023-04-22 07:01
@ich777 that's interesting that in your system `sdgyrodsu` works even when gyro is disabled in controller layout. I wonder what else is different that it's possible on your Deck.

**Comment by ich777** [comment] 2023-04-22 07:17
@kmicki I have now restarted my Deck, just to be sure it wasn't just a fluke, started Yuzu, double checked that I only have Game Controller with Camera Control enabled and it is still working (I haven't configured any Gyro in the Steam controller settings).

Are you also on the latest Steam Deck preview version? Please also note that I don't use Emudeck or something else like that, just Yuzu and your installation script.

**Comment by FoodFrisbee** [comment] 2023-06-15 05:48
@kmicki  's solution worked for me, thanks

**Comment by ich777** [comment] 2023-06-15 05:52
@kmicki just a update for you, I've now updated a few times and the gyro is still working without assigning the gyro to a button.
The only thing that I did was I set the gyro to be always on in the Steam controller settings for Yuzu instead of being activated when touching the right stick.

**Comment by BNU-BUJIDAO** [comment] 2023-06-15 11:37
steam update on June 15, and it can’t work on yuzu and Demi now😭

**Comment by anyoneyun** [comment] 2023-06-15 23:23
Same issue here on stable now, I had to enable the gyro in the controller layout section of the Steam menu

**Comment by misuzu** [comment] 2023-06-16 06:42
> 5\. Select Gyro Behavior -> Directional Pad

This fixed the issue for me.

**Comment by ratijas** [comment] 2023-06-16 19:48
@kmicki You might wanna change the title (~~beta~~) and [pin this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository), so that people won't report duplicates.

**Comment by vgf89** [comment] 2023-06-18 02:00
> > 5. Select Gyro Behavior -> Directional Pad
> 
> This fixed the issue for me.

This did not work for me, at least with Yuzu. Yuzu says it receives data from the server when I click the test button but totk doesn't get motion input.

**Comment by ich777** [comment] 2023-06-20 08:15
> This did not work for me, at least with Yuzu. Yuzu says it receives data from the server when I click the test button but totk doesn't get motion input. It worked perfectly before the most recent steam client update.

@vgf89 can you maybe test this on the `Preview` branch within SteamOS, I have no issue whatsoever on the `Preview` branch with Yuzu on my Deck.

**Comment by vgf89** [comment] 2023-06-21 00:44
> > This did not work for me, at least with Yuzu. Yuzu says it receives data from the server when I click the test button but totk doesn't get motion input. It worked perfectly before the most recent steam client update.
> 
> @vgf89 can you maybe test this on the `Preview` branch within SteamOS, I have no issue whatsoever on the `Preview` branch with Yuzu on my Deck.


There is no "Preview" branch.

For clarity, are you talking about Yuzu EA (I'm on the latest, 3698), Steam OS "Release Candidate", "Beta", "Beta Candidate", or "Main", or are you talking about Steam Client "Steam Deck Beta"?

So far I've tested Steam OS Stable/Steam Client Stable on Yuzu EA 3698, and Steam OS Release Candidate/Steam Client Stable on Yuzu EA 3698. I initially commented in this thread with Steam OS Release Candidate/Steam Client Stable and a slightly older version of Yuzu EA.

**Comment by ich777** [comment] 2023-06-21 14:44
@vgf89 I‘m not talking about Yuzu, I‘m talking about the Deck OS release channel.
In my language (German) there are thre channels: `stable`, `beta` & `preview`

On `preview` the gyro is just working fine.

On my Deck it is working regardless of the Yuzu version.

**Comment by badboybeyer** [comment] 2023-06-21 22:45
Same Issue. 

> Select Gyro Behavior -> Directional Pad

Does not work 

> set up to Action Sets->Cleared from Parent

Does not work

> Controller settings in Yuzu

I only have "mouse" and "Shake". I do not see cemuhook as an option

Testing cemuhook in yuzu gives a "Successfully received data from the server" 

"Shake" eventually shifts back to "mouse" after shaking. I have only tried this from the desktop. 

I am on preview channel for Deck OS and up to data.

I am on yuzu 1475.

I installed yuzu and cemuhookdsu using emudeck.

**Comment by JohnGhostly** [comment] 2023-06-22 20:13
> Same Issue.
> 
> > Select Gyro Behavior -> Directional Pad
> 
> Does not work
> 
> > set up to Action Sets->Cleared from Parent
> 
> Does not work
> 
> > Controller settings in Yuzu
> 
> I only have "mouse" and "Shake". I do not see cemuhook as an option
> 
> Testing cemuhook in yuzu gives a "Successfully received data from the server"
> 
> "Shake" eventually shifts back to "mouse" after shaking. I have only tried this from the desktop.
> 
> I am on preview channel for Deck OS and up to data.
> 
> I am on yuzu 1475.
> 
> I installed yuzu and cemuhookdsu using emudeck.

Having the same issue, except on stable channel.

**Comment by kmicki** [comment] 2023-06-23 15:09
> Same Issue. 
> 
> > Select Gyro Behavior -> Directional Pad
> 
> Does not work 
> 
> > set up to Action Sets->Cleared from Parent
> 
> Does not work
> 
> > Controller settings in Yuzu
> 
> I only have "mouse" and "Shake". I do not see cemuhook as an option
> 
> Testing cemuhook in yuzu gives a "Successfully received data from the server" 
> 
> "Shake" eventually shifts back to "mouse" after shaking. I have only tried this from the desktop. 
> 
> I am on preview channel for Deck OS and up to data.
> 
> I am on yuzu 1475.
> 
> I installed yuzu and cemuhookdsu using emudeck.

For me the workaround I have works on the most recent preview while using it with Cemu. So either it's an issue with yuzu or your configuration of yuzu or you're not applying the workaround correctly. I know the instructions are not detailed enough, sorry. I am going to provide more detailed workaround instructions with screenshots at some point.

As for yuzu configuration you'd need to consult yuzu users/docs.

**Comment by alexandermakalov** [comment] 2023-06-23 21:30
@JohnGhostly
>>I only have "mouse" and "Shake". I do not see cemuhook as an option
The same was for me.

Gyro is disabled by default in Desktop mode. Need to activate it.
Open steam settings(steam not system) -> Controller -> desktop layout -> edit ->  Gyro behaviour -> As Mouse
After that cemuhook will be in available in the controller settings.
As I understand, the Gyro is disabled by default for Non-steam games so we need to enabled it in the controller setting for the game.
Open Controller Settings
Edit layout
Go to Gyro
Select Gyro Behavior -> As Joystick 

Works for me.

**Comment by raccoon1267** [comment] 2023-06-24 07:15
> @JohnGhostly
> 
> > > I only have "mouse" and "Shake". I do not see cemuhook as an option
> > > The same was for me.
> 
> Gyro is disabled by default in Desktop mode. Need to activate it. Open steam settings(steam not system) -> Controller -> desktop layout -> edit -> Gyro behaviour -> As Mouse After that cemuhook will be in available in the controller settings. As I understand, the Gyro is disabled by default for Non-steam games so we need to enabled it in the controller setting for the game. Open Controller Settings Edit layout Go to Gyro Select Gyro Behavior -> As Joystick
> 
> Works for me.
Thank you for that info it work now. I have update Steam OS 3 times have not work before now it work for that info

**Comment by kmicki** [comment] 2023-06-24 07:19
Just info: if you use 'as joystick' then it's not native gyro via sdgyrodsu, Steam maps it to joystick movements which will not work e.g. for shrine puzzles in botw and other things that require native gyro.

**Comment by alexandermakalov** [comment] 2023-06-24 07:36
> Just info: if you use 'as joystick' then it's not native gyro via sdgyrodsu, Steam maps it to joystick movements which will not work e.g. for shrine puzzles in botw and other things that require native gyro.

There is no other options in the stem controller layout :( I also mapped the gyro trigger action to the right stem trigger button.  Will check how it works

**Comment by badboybeyer** [comment] 2023-06-26 18:58
I got it working. I think I may of messed up the controller configuration in yuzu. 

* I am on preview channel for Deck OS and up to data.
* I am on yuzu 1475.
* I installed yuzu and cemuhookdsu using emudeck.
* I launched yuzu in game mode using the resolution settings from @ich777 [post](https://github.com/kmicki/SteamDeckGyroDSU/issues/45#issuecomment-1518530487).
* I enabled the gyro in the steam controller setttings and set it to d-pad, always on, with the top direction bound to "Action Sets->Cleared from Parent". 
* I turned out yuzus menus (the small button with the two boxes logo + R3)
* I opened the controller settings (emulation->configuration->controls).
* I selected the profile dropdown, which was empty, then I selected "emudeck"
* I touched the motion bind button until it said "Shake". 
* I shook my deck, and it detected. Now the motion bind button says "cemuhookdsu" or something similar, its cutoff in the UI.
* I pressed the save button next to the profile dropdown.
* I pressed the apply button at the bottom of the screen
* Make sure emudeck is selected in the configuration for zelda when it is running. (emulation->configure current game->input profiles->player 1 profile->emudeck)
* I Loaded my game and checked that moving the deck moves my view
* I exited the game and undid the resolution settings (return to native resolution)
* I then actually played the game

**Comment by vgf89** [comment] 2023-07-03 12:24
Looks like my problem is that I couldn't see the Motion 1 button because the settings window was too small. By going into desktop mode and scaling the window to be slightly taller than the screen (partially covered by the taskbar) I was able to see the button, press it, and shake my deck. I couldn't do this in Game Mode as there's no way to resize arbitrary windows (changing game resolution did not change the size of the settings window), it had to be done in desktop mode. Motion works fine now. No idea how or why that setting got reset, hopefully Yuzu can fix that UI.

**Comment by punkos91** [comment] 2023-07-09 10:36
> I got it working. I think I may of messed up the controller configuration in yuzu.
> 
> * I am on preview channel for Deck OS and up to data.
> * I am on yuzu 1475.
> * I installed yuzu and cemuhookdsu using emudeck.
> * I launched yuzu in game mode using the resolution settings from @ich777 [post](https://github.com/kmicki/SteamDeckGyroDSU/issues/45#issuecomment-1518530487).
> * I enabled the gyro in the steam controller setttings and set it to d-pad, always on, with the top direction bound to "Action Sets->Cleared from Parent".
> * I turned on yuzus menus (view + R3) [reference controller buttons](https://www.androidheadlines.com/wp-content/uploads/2021/07/Steam-Deck-Controls-2.jpg)
> * I opened the controller settings (emulation->configuration->controls).
> * I selected the profile dropdown, which was empty, then I selected "emudeck"
> * I touched the motion bind button until it said "Shake".
> * I shook my deck, and it detected. Now the motion bind button says "cemuhookdsu" or something similar, its cutoff in the UI.
> * I pressed the save button next to the profile dropdown.
> * I pressed the apply button at the bottom of the screen
> * Make sure emudeck is selected in the configuration for zelda when it is running. (emulation->configure current game->input profiles->player 1 profile->emudeck)
> * I Loaded my game and checked that moving the deck moves my view
> * I exited the game and undid the resolution settings (return to native resolution)
> * I then actually played the game
> 
> Update:
> 
> The next time I booted the game, the gyro was not working again. I had to select the emudeck profile again from the the controller settings (emulation->configuration->controls). Maybe I need to make a default layout and repeat this process?

This is the only thing that worked for me. 
And after desactivate, in game the steam controller setting about the gyro. 
Will try if it stays next time i start the game

**Comment by Roszadok** [comment] 2023-07-28 19:53
> Grimbakor from the Yuzu Discord has made a video on how to enable it, the main issue was that you have to click the button in the middle in the Controller settings in Yuzu and not on the other option which most Youtube videos recommend. He allowed me to upload his videos here.
> 
> This is if you are doing it from the Desktop mode (you have to make the screen actually bigger because otherwise you won't be able to click the button):
> 
>  gyro.mp4 
> And this is what you have to do when you do it from within Gaming Mode (you have to set a custom resolution in order to be able to click the button):
> 
>  output.mp4 
> BTW, I don't have to do the workaround that you've posted above @kmicki, the gyro is in my case always active even when using a Controller layout without Gyro.

I did every step within this thread and I can only setup from 1st video but doing it like in 2nd video it do not work at all

**Comment by schspa** [comment] 2023-10-11 09:18
> Yes there is a problem with new Beta. Steam disables gyro input from the controller when Gyro in controller settings is set to "None".
> 
> As a workaround (I assume Cemu/Yuzu is run in gaming mode from Steam):
> 
> 1. Press STEAM button
> 2. Open Controller Settings
> 3. Edit layout
> 4. Go to Gyro
> 5. Select Gyro Behavior -> Directional Pad
> 6. Choose anything for one of the positions of directional pad. Anything that won't intefere with using Cemu/Yuzu. I chose Action Sets->Cleared from Parent
> 7. Now it should work.

How to set Gyro Behavior -> Directional Pad, I only see mouse and joystick 😂.

**Comment by kmicki** [comment] 2023-10-15 12:16
> @kmicki You might wanna change the title (~beta~) and [pin this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository), so that people won't report duplicates.

Thanks, done.

**Comment by TheBoxyBear** [comment] 2023-10-28 19:00
> > Yes there is a problem with new Beta. Steam disables gyro input from the controller when Gyro in controller settings is set to "None".
> > As a workaround (I assume Cemu/Yuzu is run in gaming mode from Steam):
> > 
> > 1. Press STEAM button
> > 2. Open Controller Settings
> > 3. Edit layout
> > 4. Go to Gyro
> > 5. Select Gyro Behavior -> Directional Pad
> > 6. Choose anything for one of the positions of directional pad. Anything that won't intefere with using Cemu/Yuzu. I chose Action Sets->Cleared from Parent
> > 7. Now it should work.
> 
> How to set Gyro Behavior -> Directional Pad, I only see mouse and joystick 😂.

It now seens to be hidden from the general settings. You have to open the gyro specific settings and there Directional Pad appears in the dropdown although even this isn't working for me even though the server test passes in Yuzu.

**Comment by kmicki** [comment] 2023-10-28 19:57
> although even this isn't working for me even though the server test passes in Yuzu.

I have just tested it in a most recent preview with PadTest and Cemu and workaround still works. Maybe there's another issue. Can you try [PadTest](https://files.sshnuke.net/PadTest_1011.zip)? It has to be run using Proton GE or from another Windows PC.

**Comment by TheBoxyBear** [comment] 2023-10-28 20:10
> > although even this isn't working for me even though the server test passes in Yuzu.
> 
> I have just tested it in a most recent preview with PadTest and Cemu and workaround still works. Maybe there's another issue. Can you try [PadTest](https://files.sshnuke.net/PadTest_1011.zip)? It has to be run using Proton GE or from another Windows PC.

I'll try when I get the chance, though I also noticed the Motion 1 option below the controller layout only appears for Players 2+

**Comment by vgf89** [comment] 2023-10-29 00:32
I think the off-screen Motion 1 button is the root cause of the problem when just messing with Steam Input doesn't fix it. I was able to make it appear by messing with the window size in desktop mode so I could click it. If you've got a dock that makes things easier. But seriously, the button should show up on controller 1 and it doesn't because something is different.

I'm going to have to get the Yuzu build chain set up and fix it myself for a PR aren't I...

**Comment by TheBoxyBear** [comment] 2023-10-29 19:20
> I think the off-screen Motion 1 button is the root cause of the problem when just messing with Steam Input doesn't fix it. I was able to make it appear by messing with the window size in desktop mode so I could click it and get motion working and it hasn't broken since. If you've got a dock that makes things a little easier. But seriously, the button should show up on controller 1 in gaming mode or on small screens, and it doesn't because something is different on controller 1's layout specifically.
> 
> I'm going to have to get the Yuzu build chain set up and fix it myself for a PR aren't I...

I tried with a dock in 1080p and it still wasn't there even though it should have the space for at least part of it.

**Comment by TheBoxyBear** [comment] 2023-11-02 00:43
> I think the off-screen Motion 1 button is the root cause of the problem when just messing with Steam Input doesn't fix it. I was able to make it appear by messing with the window size in desktop mode so I could click it and get motion working and it hasn't broken since. If you've got a dock that makes things a little easier. But seriously, the button should show up on controller 1 in gaming mode or on small screens, and it doesn't because something is different on controller 1's layout specifically.
> 
> I'm going to have to get the Yuzu build chain set up and fix it myself for a PR aren't I...

It was a layout bug after all although even with an external monitor, it wouldn't show. What ended up working was with the deck's screen, only stretch the window vertically and dragging it down. With an awkward size and position, it's possible to access the Motion button, although Steam has to not be running in order to be assigned by shaking. The configuration now remains in gaming mode but I now have the common issue of gyro only working with the options panel open.

**Closed as completed** 2023-11-10 12:18 UTC
